### ISSUE TITLE
关于歌曲资源获取

### ISSUE THREAD

**Issue by cryptopunkg** [wangruns/Hybrid-Music-Recommender-System#4]
想请教一下大佬，本项目的数据库 song表里面的200多首歌曲是如何获取的呢？要手工一首一首的下载到当前项目 的   /track/song/ 文件夹下面吗？同问200多首歌曲对应的歌词资源。感觉一首一首去下载工作量很大啊。

**Comment by wangruns** [comment]
是的，工作量确实有，我当时是选择了自己喜欢的200来首，你也可以选择你自己喜欢的或者其他；歌词的话，不是必须的，可以不用。

**Comment by cryptopunkg** [comment]
不是哪个PTE模型，W2W和W2D词嵌入那边，需要歌词的吗？没有歌词怎么训练呢？

**Comment by wangruns** [comment]
对于系统运行来说，歌词不是必须的；对于W2W和W2D的话，歌词可能也只能你自己下载了...

**Comment by UpUrHands** [comment]
而且下载了还要管理员再点几下
