### ISSUE TITLE
up主，我下的myeclispe10+JDK1.8，这个src/main/java下的文件左下角几乎都有X号，是JDK版本的问题吗

### ISSUE THREAD

**Issue by caihong69** [wangruns/Hybrid-Music-Recommender-System#5]
类似于这种的错：The type java.util.Map$Entry cannot be resolved. It is indirectly referenced from required .class files

**Comment by wangruns** [comment]
可能是myeclispe10的版本问题，你可以尝试升级为更高的版本如myeclipse2014试试看，或者更建议用和本项目一致的Eclipse
