### ISSUE TITLE
关于词嵌入

### ISSUE THREAD

**Issue by cryptopunkg** [wangruns/Hybrid-Music-Recommender-System#6]
想请教一下大佬，关于algorithm包里面的几个关于词嵌入算法的类具体是用的什么数学公式呢？求大佬给一个膜拜论文的机会。因为我看词嵌入的那几个类实在是看不懂，不知道是基于什么数学公式的。如果能知道数学公式或者算法解释九太棒啦

**Comment by Merak2** [comment]
你有实现他的源码吗？我今天试了一天，实现出来发现明显应付毕业设计的（可能代码有写，没有仔细研究）。
**！！！！！网页端根本实现不了推荐！！！！！！！！**

**Comment by caihong69** [comment]
你好，我也在弄这个。有些问题，能交流下吗？QQ：2449802046

**Comment by liminliying** [comment]
主要还是算法，不知道大佬有没有时间弄个基础的文档，让我学习下呢？
951329137@qq.com, 希望能与大佬交流

**Comment by wangruns** [comment]
关于词嵌入的算法可以从References里面的这个了解
PTE: Predictive Text Embedding through Large-scale Heterogeneous Text Networks. Jian Tang, Meng Qu, Qiaozhu Mei. KDD 2015.-1508.00200
