### ISSUE TITLE
你好up主

### ISSUE THREAD

**Issue by caihong69** [wangruns/Hybrid-Music-Recommender-System#7]
请问，我导.sql脚本的时候，出现Error Code : 1100. Table 'collection' was not locked with LOCK TABLES   怎么解决啊？

**Comment by hyb4078** [comment]
> 
> 
> 请问，我导.sql脚本的时候，出现Error Code : 1100. Table 'collection' was not locked with LOCK TABLES 怎么解决啊？

@caihong69 
我这边执行脚本都OK的，建议你先在网上寻找一下答案，如果已解决建议关闭该 Issue 。

**Comment by caihong69** [comment]
好的，谢谢！
